model_type: 'melgan'
model_name: 'welt_predtuning'

paths:
  train_dir: '/Users/cschaefe/datasets/stylemelgan_welt_train'
  train_dir_mels: '/Users/cschaefe/datasets/finetuning/bild_welt_masked_mels'
  val_dir: '/Users/cschaefe/datasets/stylemelgan_welt_fuckup'
  checkpoints: 'stylemelgan/checkpoints'

audio:
  sample_rate: 22050
  n_mels: 80
  n_fft: 1024
  win_length: 1024
  hop_length: 256
  fmin: 0
  fmax: 8000

training:
  batch_size: 2
  batch_size_mel: 2
  pretraining_steps: 200000
  segment_len: 8192
  segment_len_mel: 8192
  g_lr: 0.0001
  d_lr: 0.0001
  eval_steps: 100
  epochs: 100000
  num_workers: 6

model:
  channels: [512, 256, 128, 64, 32]
  res_layers: [5, 7, 8, 9]
  relu_slope: 0.2
  padding_val: -11.5129